!!python/object:config.JobConfig
actor_nn_size: [128, 128]
batch_norm: true
batch_size: 256
buffer_size: 100000
clip_grad_norm: true
critic_nn_size: [128, 128]
damp_exploration_noise: false
gamma: 1
lr_actor: 0.0001
lr_critic: 0.0001
max_score: 0.5
n_episodes: 2500
print_every: 50
random_seed: 0
score_window_size: 100
sigma: 0.1
tau: 0.001
weight_decay: 0
